### ISSUE TITLE
为何不起效

### ISSUE THREAD

**Issue by leoterry-ulrica** [WeihanLi/WeihanLi.DataProtection#1]
services.AddDataProtection().AddParamsProtection(options => {
                options.ProtectParams = new[] 
                {
                    "id"
                };
            });
返回结果的id依然是原值。
请问哪里配置错了吗？

**Comment by WeihanLi** [comment]
你的控制器里的返回的结果是什么呢？现在只对 `OkObjectResult` 有效？

**Comment by leoterry-ulrica** [comment]
返回结果是自定义的一个DTO

**Comment by WeihanLi** [comment]
你的 Action 的代码可以展示一下吗，示例代码就可以，不需要完整的，类似于这样的

``` csharp
return OK(new { Id = 123, Name= "abc" });
```

**Comment by leoterry-ulrica** [comment]
return base.Success([{Id = 322, Name = "test"}]);

**Comment by WeihanLi** [comment]
`base.Success` 返回的是一个 `JsonResult` 吗？
如果是 `JsonResult` 使用 0.3.0 的包，按照示例项目配置可以实现参数保护

**Comment by leoterry-ulrica** [comment]
那我知道了，返回结果是一定要是JsonResult 这个类型，对吧

**Comment by WeihanLi** [comment]
默认支持 ObjectResult , JsonResult 需要配置，其他的话应该也可以配置，需要看一下，你的代码有公开吗，我帮你看下

**Comment by leoterry-ulrica** [comment]
公司代码没有公开，谢谢！

**Comment by WeihanLi** [comment]
什么类型没有关系，即使是自定义的类型也可以，在 Startup 里注册就可以了，`TResult` 是你返回的类型，应该是要实现 `IActionResult` 的，后面要指出要保护的值，以 `JsonResult` 为例，注册代码如下：

``` csharp
// Protect JsonResult
options.AddProtectValue<JsonResult>(r => r.Value);
```

看上面的代码，感觉应该是在 `JsonResult` 的基础上封装了一层，你可以看一下 `base.Success` 的返回值

**Comment by WeihanLi** [comment]
除了这个示例项目，我在另外一个项目里也有配置保护返回的 `JsonResult` 中的参数，可以参考
<https://github.com/WeihanLi/AccountingApp/blob/master/AccountingApp/Startup.cs#L61>

这个 issue 我先关掉了，还有问题的话可以再打开或新建
